### ISSUE TITLE
Trello-Github Plugin kurulması

### ISSUE THREAD

**Issue by umieat** [umieat/react-sutime#14]
┆Attachments: <a href="https:&#x2F;&#x2F;github.com&#x2F;bekorn&#x2F;betterweb&#x2F;issues&#x2F;14">#14 Authentication for Google Account Login via Socialite</a>

**Comment by umieat** [comment]
➤ Berk Canli commented:

Sanırım yaptım. Githubdaki labellar da geldi. Şimdi issueyu kapatmayı deneyeceğim

**Comment by bekorn** [comment]
Bunu kapatırsan kart da gidecek mi acaba??

**Comment by umieat** [comment]
Issue'yi kapatınca trellodaki kart da otomatik olarak gitti.
